[Interface]
PrivateKey = 8njEONvsdL36xb8BLbMDgPq8naterWTbdhzVFmYmPO4=
Address = 10.10.2.135/32
DNS = 8.8.8.8, 1.1.1.1

[Peer]
PublicKey = u99ieORdpGIytOzLrvJQl5VRanc+SiXM2DbH63kizwg=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 45.144.19.250:8585
PersistentKeepalive = 10
